bst
agarwalvickey8/data_structure pull request #2
Opened 2023-01-04 07:31 UTC by agarwalvickey8

2023-01-04 09:26 UTC, SparshAgrawal1 commented on binary_search_tree.rb
> +  def initialize()
no need of brackets

2023-01-04 09:27 UTC, SparshAgrawal1 commented on binary_search_tree.rb
> +   if @root == nil
if self.root.nil?

use self.root instead of @root

2023-01-04 09:27 UTC, SparshAgrawal1 commented on binary_search_tree.rb
> +     previous_node = @root
use self.root

2023-01-04 09:27 UTC, SparshAgrawal1 commented on binary_search_tree.rb
> +     while current_node != nil
while !current.node.nil?

2023-01-04 09:28 UTC, SparshAgrawal1 commented on binary_search_tree.rb
> +    return nil
return nil if node.nil?

2023-01-04 09:29 UTC, SparshAgrawal1 commented on binary_search_tree.rb
> +    return node.value
return node.value if node.right.nil?

2023-01-04 09:29 UTC, SparshAgrawal1 commented on binary_search_tree.rb
> +    return nil
return nil if node.nil?

2023-01-04 09:29 UTC, SparshAgrawal1 commented on binary_search_tree.rb
> +    return node.value
return node.value if node.left.nil?

2023-01-04 09:30 UTC, SparshAgrawal1 commented on binary_search_tree.rb
> +    return smallest_element(root.left)
no need to write return at the last return
only smallest_element(root.left)

2023-01-04 09:36 UTC, SparshAgrawal1 commented on binary_search_tree.rb
> +  if node == nil
return if node.nil?

2023-01-04 09:37 UTC, SparshAgrawal1 commented on binary_search_tree.rb
> +  print(" ")
print "#{node.value} "

2023-01-04 09:37 UTC, SparshAgrawal1 commented on binary_search_tree.rb
> +    return
return if node.nill?

2023-01-04 09:37 UTC, SparshAgrawal1 commented on binary_search_tree.rb
> +    print(" ")
print "#{node.value} "

2023-01-04 09:37 UTC, SparshAgrawal1 commented on binary_search_tree.rb
> +    return
return if node.nill?

2023-01-04 09:37 UTC, SparshAgrawal1 commented on binary_search_tree.rb
> +  print(" ")
print "#{node.value} "

2023-01-04 09:38 UTC, SparshAgrawal1 commented on binary_search_tree.rb
> +    return
return if node.nil?

2023-01-04 09:38 UTC, SparshAgrawal1 commented on binary_search_tree.rb
> +  print(" ")
print "#{node.value} "

2023-01-04 09:39 UTC, SparshAgrawal1 commented on binary_search_tree.rb
> +    return false
return false if node.nil?

2023-01-04 09:39 UTC, SparshAgrawal1 commented on binary_search_tree.rb
> +    return true
return true if element == node.value

2023-01-04 09:41 UTC, SparshAgrawal1 commented on binary_search_tree.rb
> +  else if node.value > element
elsif element < node.value

2023-01-04 09:41 UTC, SparshAgrawal1 commented on binary_search_tree.rb
> +    return nil
return nil if node.nil?

2023-01-04 09:41 UTC, SparshAgrawal1 commented on binary_search_tree.rb
> +  if node.value > value
if value < node.value

2023-01-04 09:42 UTC, SparshAgrawal1 commented on binary_search_tree.rb
> +    if node.left != nil && node.right != nil
elsif node.left.nil? && node.right.nil?

2023-01-04 09:42 UTC, SparshAgrawal1 commented on binary_search_tree.rb
> +    elsif node.left != nil
elsif node.left.nil?

2023-01-04 09:42 UTC, SparshAgrawal1 commented on binary_search_tree.rb
> +    elsif node.right != nil
elsif node.right.nil?

2023-01-04 09:42 UTC, SparshAgrawal1 commented on binary_search_tree.rb
> +  return node
node

~no return~

2023-01-04 09:43 UTC, SparshAgrawal1 commented on binary_search_tree.rb
> +    num_values=gets.chomp()
do as per defined that is comma-separated input

2023-01-04 09:44 UTC, SparshAgrawal1 commented on binary_search_tree.rb
> +    puts(largest_element(root))
largest_element function should return the element 
it should not print it

2023-01-04 09:45 UTC, SparshAgrawal1 commented on binary_search_tree.rb
> +    puts(smallest_element(root))
smallest_element function  should return the element
it should not print it

2023-01-04 09:45 UTC, SparshAgrawal1 commented on binary_search_tree.rb
> +    print(search_element(root,element)
search element should return the boolean type, it should not print it

2023-01-04 09:46 UTC, SparshAgrawal1 commented on binary_search_tree.rb
> +    print("exit")
when user decides to exit, you should also put the elements of the binary search tree in one separate file (output.txt)

2023-01-04 09:47 UTC, SparshAgrawal1 requested changes
Many changes are required

2023-01-05 07:55 UTC, bv-hemant reviewed
test it. It will break

2023-01-05 07:55 UTC, bv-hemant commented on binary_search_tree.rb
> +end
use tab not space

2023-01-05 07:55 UTC, bv-hemant commented on binary_search_tree.rb
> +  end
have you tested it?

2023-01-05 11:00 UTC, bv-hemant requested changes
test it properly

2023-01-05 11:00 UTC, bv-hemant commented on binary_search_tree.rb
> +			end
use ternary

2023-01-05 11:00 UTC, bv-hemant commented on binary_search_tree.rb
> +	return largest_element(node.right)
no need of return in last

2023-01-05 11:00 UTC, bv-hemant commented on binary_search_tree.rb
> +def largest_element(node=self.root)
node = self.root

2023-01-05 11:00 UTC, bv-hemant commented on binary_search_tree.rb
> +def smallest_element(node=self.root)
node = slef.root

2023-01-05 11:00 UTC, bv-hemant commented on binary_search_tree.rb
> +	print"#{node.value}"
print "#{node.value} "

2023-01-05 11:00 UTC, bv-hemant commented on binary_search_tree.rb
> +	print(" ")
no need

2023-01-05 11:00 UTC, bv-hemant commented on binary_search_tree.rb
> +	print"#{node.value}"
print "#{node.value} "

2023-01-05 11:00 UTC, bv-hemant commented on binary_search_tree.rb
> +def pre_order(node=self.root)
node  = self.root

2023-01-05 11:00 UTC, bv-hemant commented on binary_search_tree.rb
> +  print(" ")
no need

2023-01-06 06:05 UTC, bv-hemant requested changes

2023-01-06 06:05 UTC, bv-hemant commented on binary_search_tree.rb
> +			self.root = Tree.new(value)
TreeNode

2023-01-06 06:05 UTC, bv-hemant commented on binary_search_tree.rb
> +class Tree
TrreNode

2023-01-06 06:05 UTC, bv-hemant commented on binary_search_tree.rb
> +		if self.root.nil?
indentation

2023-01-06 06:05 UTC, bv-hemant commented on binary_search_tree.rb
> +		return largest_element(node.right)
no need of return

2023-01-06 06:05 UTC, bv-hemant commented on binary_search_tree.rb
> +		print(" ")
print "#{node.value} "

2023-01-06 06:05 UTC, bv-hemant commented on binary_search_tree.rb
> +		print(" ")
print "#{node.value} "

2023-01-06 06:05 UTC, bv-hemant commented on binary_search_tree.rb
> +		print(" ")
print "#{node.value} "

2023-01-06 06:05 UTC, bv-hemant commented on binary_search_tree.rb
> +	def search_element(node = self.root,element)
def search_element(node = self.root, element)

2023-01-06 06:05 UTC, bv-hemant commented on binary_search_tree.rb
> +	def all_path(node = self.root, arr)
what is arr? give proper naming

2023-01-06 06:05 UTC, bv-hemant commented on binary_search_tree.rb
> +		end
print " #{arr}" if node.left.nil? && node.right.nil?

2023-01-06 06:05 UTC, bv-hemant commented on binary_search_tree.rb
> +			if(node.left.nil? && node.right.nil?)
why brackets?

2023-01-06 06:05 UTC, bv-hemant commented on binary_search_tree.rb
> +	def elements_file(node = self.root)
give proper naming. 
and fix this

2023-01-06 06:05 UTC, bv-hemant commented on binary_search_tree.rb
> +	end
take input outside the class

2023-01-06 06:05 UTC, bv-hemant commented on binary_search_tree.rb
> +		for i in 1..elements.length
elements.each { |element| insert(element) }

2023-01-06 06:05 UTC, bv-hemant commented on binary_search_tree.rb
> +			puts "Default value"
do this all things outside the class

2023-01-06 06:05 UTC, bv-hemant commented on binary_search_tree.rb
> +	while(!loop_end)
while true

2023-01-06 06:05 UTC, bv-hemant commented on binary_search_tree.rb
> +		operation_num = gets.chomp()
why brackets

2023-01-06 06:05 UTC, bv-hemant commented on binary_search_tree.rb
> +			end
do as per task

2023-01-06 06:05 UTC, bv-hemant commented on binary_search_tree.rb
> +			print(largest_element)
if no largest element

2023-01-06 06:05 UTC, bv-hemant commented on binary_search_tree.rb
> +			print(smallest_element)
if no smallest element

2023-01-06 06:05 UTC, bv-hemant commented on binary_search_tree.rb
> +		when 8
why do you need to send root

2023-01-06 06:05 UTC, bv-hemant commented on binary_search_tree.rb
> +			element = gets.chomp()
why brackets

2023-01-06 06:05 UTC, bv-hemant commented on binary_search_tree.rb
> +			arr = Array.new
proper naming and why you are sending root

2023-01-06 06:05 UTC, bv-hemant commented on binary_search_tree.rb
> +			name = gets()
if file does not exist then

2023-01-06 06:05 UTC, bv-hemant commented on binary_search_tree.rb
> +		else
rethink and fix this

2023-01-06 06:05 UTC, bv-hemant commented on binary_search_tree.rb
> +			puts "Default value"
what is this?

2023-01-06 08:04 UTC, bv-hemant requested changes

2023-01-06 08:04 UTC, bv-hemant commented on binary_search_tree.rb
> +	def insert(value)
add extra line between two function

2023-01-06 08:04 UTC, bv-hemant commented on binary_search_tree.rb
> +			while current_node?
current_node

2023-01-06 08:04 UTC, bv-hemant commented on binary_search_tree.rb
> +	def all_path(node = self.root, elements_array)
elements

2023-01-06 08:04 UTC, bv-hemant commented on binary_search_tree.rb
> +fileobject = File.new("elements_file.txt", "a+")
file

2023-01-06 08:04 UTC, bv-hemant commented on binary_search_tree.rb
> +	elements = fileobject.read()
input and output files are same?

2023-01-06 08:04 UTC, bv-hemant commented on binary_search_tree.rb
> +while(true)
no need of bracket

2023-01-06 08:04 UTC, bv-hemant commented on binary_search_tree.rb
> +		end
element_values_array.each { |element| bst.insert(element.to_i) }

2023-01-09 13:29 UTC, bv-hemant requested changes

2023-01-09 13:29 UTC, bv-hemant commented on binary_search_tree.rb
> +root = BST.new
bst

2023-01-09 13:29 UTC, bv-hemant commented on binary_search_tree.rb
> +	def search_element(node = self.root, element)
def search_element( element, node = self.root)

2023-01-09 13:29 UTC, bv-hemant commented on binary_search_tree.rb
> +	def all_path(node = self.root, elements)
def all_path(elements, node = self.root)

2023-01-09 13:29 UTC, bv-hemant commented on binary_search_tree.rb
> +		bst ? print(bst.largest_element) : print("Currently BST is empty")
print bst ?  bst.largest_element : "Currently BST is empty"

2023-01-09 13:29 UTC, bv-hemant commented on tree.rb
> +			search_element(element)
print

2023-01-09 13:29 UTC, bv-hemant commented on tree.rb
> +			end
one liner

2023-01-09 13:29 UTC, bv-hemant commented on tree.rb
> +			all_paths(root,arr)
space after `,`

2023-01-09 13:29 UTC, bv-hemant commented on tree.rb
> +		operation_num = gets.chomp()
why empty brackets?

2023-01-09 13:29 UTC, bv-hemant commented on tree.rb
> +			name = gets()
why empty brackets?

2023-01-10 05:19 UTC, bv-hemant requested changes

2023-01-10 05:19 UTC, bv-hemant commented on binary_search_tree.rb
> +		arr.pop()
where is arr defined?

2023-01-10 05:19 UTC, bv-hemant commented on binary_search_tree.rb
> +		make_bst(self.elements)
where is the function

2023-01-10 05:19 UTC, bv-hemant commented on binary_search_tree.rb
> +fileobject = File.open("file.txt", "w+")
why?

2023-01-10 05:19 UTC, bv-hemant commented on binary_search_tree.rb
> +		bst.search_element(element.to_i)
print?

2023-01-10 05:19 UTC, bv-hemant commented on binary_search_tree.rb
> +		print(bst.remove_element(element.to_i))
no need of brackets in print

2023-01-10 05:19 UTC, bv-hemant commented on binary_search_tree.rb
> +		end
one liner

2023-01-10 05:19 UTC, bv-hemant commented on binary_search_tree.rb
> +		bst.add_elements_to_file(fileobject)
change the file name

2023-01-10 05:19 UTC, bv-hemant commented on binary_search_tree.rb
> +		bst.add_elements_to_file(fileobject)
make the fileobject local

2023-01-15 11:23 UTC, closed without merging